import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import React from "react";

import { cn } from "@/lib/utils"

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "EShop",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        inter.variable
      )}>
        <main className="flex flex-col items-center p-24 min-h-screen justify-between">
          {children}
        </main>
      </body>
    </html>
  )
}
